require 'sqlite3'

db = SQLite3::Database.new('ideas.db')

# All the curated stupid ideas from the original HTML
ideas = [
  "A restaurant where all the food is shaped like tiny furniture",
  "Shoes with built-in bubble wrap on the soles for constant popping",
  "A social media platform exclusively for posting pictures of receipts",
  "Inflatable dartboard for safety-conscious dart enthusiasts",
  "A gym membership that only works during full moons",
  "Edible post-it notes in various flavors",
  "A streaming service that only shows the credits of movies",
  "Sunglasses for your knees to prevent knee sunburn",
  "A dating app that matches people based on their grocery store receipts",
  "Waterproof tea bags for underwater tea parties",
  "A keyboard where every key types the letter 'Q'",
  "Socks with individual compartments for each toe hair",
  "A pillow that plays elevator music when you lay on it",
  "Transparent highlighters for invisible studying",
  "A phone case made entirely of soap for easy cleaning",
  "Reverse umbrella that collects rain instead of blocking it",
  "A microwave that only heats food to room temperature",
  "Books with blank pages for people who enjoy the smell but not the reading",
  "A calendar that only shows Wednesdays",
  "Gloves with built-in pencil sharpeners on each fingertip",
  "A coffee maker that turns coffee back into beans",
  "Mirrors that only show you from the neck down",
  "Headphones that play other people's thoughts instead of music",
  "A toaster that untoasts bread back to its original softness",
  "Sticky notes that lose their stickiness immediately after application",
  "A treadmill that moves backwards so you never make progress",
  "Ice cubes that heat up your drink",
  "A lamp that produces darkness instead of light",
  "Edible clothing for emergency snacks",
  "A smoke detector that celebrates when it detects smoke",
  "Glasses that make everything look slightly to the left",
  "A doorbell that rings inside your head",
  "Flavored dental floss: now in anchovy and dirt flavors",
  "A selfie stick for taking pictures of other people",
  "A car horn that plays compliments to other drivers",
  "Socks that automatically become mismatched in the dryer",
  "A remote control for your remote control",
  "Paint that becomes invisible after it dries",
  "A watch that only tells you what time it isn't",
  "Headphones that only play the bass line of any song",
  "A flashlight that only works in broad daylight",
  "Edible napkins that taste like the food you're eating",
  "A GPS that only gives directions to places you've already been",
  "Soundproof headphones that amplify all sounds",
  "A diary that automatically deletes everything you write",
  "Shoes that tie themselves into knots randomly",
  "A phone charger that drains your battery faster",
  "Sunscreen that makes you more susceptible to sunburn",
  "A fan that blows hot air only",
  "Bluetooth-enabled rocks for the modern stone collector",
  "A refrigerator that compliments your food as it spoils",
  "Jeans with pockets that have holes in the bottom",
  "A pen that writes in invisible ink but you can't read it either",
  "Headphones that swap the left and right audio channels randomly",
  "A plant that wilts when you water it and thrives when you ignore it",
  "Eyeglasses that show you the world in standard definition",
  "A keyboard that autocorrects to make everything sound pretentious",
  "Bread that slices itself at random angles",
  "A scale that shows your weight in feelings instead of numbers",
  "An alarm clock that wakes up everyone except you",
  "A map that's always upside down",
  "Shoes with shoelaces that tie themselves to other people's shoes",
  "A coffee mug that judges your life choices",
  "Headphones that play a commentary track for your own life",
  "A fitness tracker that counts steps backwards",
  "An oven mitt that conducts heat better than bare hands",
  "A bookmark that loses your place in the book",
  "An eraser that makes pencil marks permanent",
  "A hammock made of sandpaper",
  "A snow globe of your daily commute",
  "Transparent windows for your wallet so everyone can see you're broke",
  "A motivational poster that just says 'meh'",
  "An infinity pool that's actually just a puddle",
  "Fortune cookies that tell you your embarrassing past",
  "A newspaper that only reports on things that didn't happen",
  "Cologne that smells like expired milk",
  "A calculator that only does incorrect math",
  "Wireless charging cables",
  "An app that unorganizes your files",
  "A thermostat that sets itself to the most uncomfortable temperature",
  "Scratch-and-sniff wallpaper in wet dog scent",
  "Elevator music for your stairs"
]

# Clear existing ideas
db.execute('DELETE FROM ideas')

# Insert all ideas
ideas.each do |idea|
  db.execute('INSERT INTO ideas (idea) VALUES (?)', [idea])
end

puts "Successfully seeded #{ideas.length} ideas into the database!"
